"""add calibration_snapshots

Revision ID: 539a4fc7aaa7
Revises: 616ab0483dd6
Create Date: 2026-07-23 00:06:22.291417
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '539a4fc7aaa7'
down_revision: str | None = '616ab0483dd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('seq_weight', sa.Float(), nullable=False),
    sa.Column('stat_weight', sa.Float(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('precision_before', sa.Float(), nullable=False),
    sa.Column('recall_before', sa.Float(), nullable=False),
    sa.Column('precision_after', sa.Float(), nullable=False),
    sa.Column('recall_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_snapshots_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calibration_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_snapshots_created_at'))

    op.drop_table('calibration_snapshots')
    # ### end Alembic commands ###
